on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@master
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@master
      with:
         path: './src/github.com/github-release/github-release'
    # staticcheck needs this for GOPATH
    - run: echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - run: echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Run tests
      run: make lint test
      working-directory: './src/github.com/github-release/github-release'
