 - name: build artifacts
    run: make build-windows
- name: upload windows artifact
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: ./bin/windows-amd64-github-release.zip
      asset_name: windows-amd64-github-release.zip
      asset_content_type: application/zip
